# -*- coding: utf-8 -*-
"""tabuada-digital.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ApuYvzMcTHvTQnMs736nDco8e0JmHhJ
"""

import random
pontuação = 0
acertos = 0
erros = 0

while True:
  jogar = input('deseja jogar? (s/n)\t').lower()
  if  jogar == 's':
    for i in range(0, 5):
      print('você tem direito à 5 tentativas')
      num1 = random.randint(0, 9)

      operação = random.randint(0, 4)
      num2 = random.randint(0, 9)

      while True:
        if num2 == 0 and operação == 1:
          num2 = random.randint(1, 9)
        else:
          break

      if operação == 0:
        resultado = num1 + num2
        resposta_user = float(input(f'qual o resultado de:\t{num1} + {num2} = ?\t'))
      elif operação == 1:
        resultado = num1 / num2
        resposta_user = float(input(f'qual o resultado de:\t{num1} / {num2} = ?\t'))
      elif operação == 2:
        resultado = num1 - num2
        resposta_user = float(input(f'qual o resultado de:\t{num1} - {num2} = ?\t'))
      else:
        resultado = num1 * num2
        resposta_user = float(input(f'qual o resultado de:\t{num1} * {num2} = ?\t'))

      if resposta_user == resultado:
            pontuação += 1
            acertos += 1
            print('parabéns, você acertou!')
      else:
        erros += 1
        pontuação -=1
        print('que pena... você errou!')

  else:
      break
print(f'\npontuação total:\t{pontuação}\n número de acertos:\t{acertos}\n número de erros:\t{erros}.\n')
print('encerrando...')